version: '3'

services:
  web:
    image: bohendo/nginx:1.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - bjvm-net
    ports:
      - "80:80"

networks:
  bjvm-net:
